2021-03-17 20:15:54,799 INFO: Microblog startup [in C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\__init__.py:47]
2021-03-17 21:10:00,657 ERROR: Exception on /reset_password_request [POST] [in c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\studyuser\pycharmprojects\hu_cloud-infrastructure-and-management\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: module 'jwt' has no attribute 'encode'
2021-03-19 14:38:32,713 INFO: Microblog startup [in C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\__init__.py:47]
2021-03-19 14:40:58,460 INFO: Microblog startup [in C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\__init__.py:47]
2021-03-19 14:42:26,008 INFO: Microblog startup [in C:\Users\StudyUser\PycharmProjects\HU_Cloud-Infrastructure-and-Management\mircoblog\app\__init__.py:47]
